stages:
  - validate
  - deploy

variables:
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_CONFIG: "ansible/ansible.cfg"
  GITLAB_HOST: "192.168.0.213"  # آیپی سرور شما
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"  # کلید SSH از متغیرهای GitLab

before_script:
  - apt-get update -qq && apt-get install -y -qq ansible git sshpass
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

validate:
  stage: validate
  image: python:3.9
  script:
    - pip install ansible ansible-lint
    - ansible-lint ansible/playbooks/*.yml
    - ansible-playbook ansible/playbooks/01-docker.yml --syntax-check
    - ansible-playbook ansible/playbooks/02-gitlab.yml --syntax-check
  only:
    - merge_requests

deploy_docker:
  stage: deploy
  image: python:3.9
  script:
    - pip install ansible
    - ansible-playbook -i ansible/inventory/env_inventory.py ansible/playbooks/01-docker.yml --become --become-method=sudo --become-user=root
  only:
    - main

deploy_gitlab:
  stage: deploy
  image: python:3.9
  script:
    - pip install ansible
    - ansible-playbook -i ansible/inventory/env_inventory.py ansible/playbooks/02-gitlab.yml --become --become-method=sudo --become-user=root
    - echo "Waiting for GitLab to initialize (3 minutes)..."
    - sleep 180  # تأخیر برای راه‌اندازی کامل GitLab
    - |
      echo "GitLab should be available at:"
      echo "http://$GITLAB_HOST"
      echo "http://$GITLAB_HOST:2222"  # اگر پورت SSH را تغییر دادید
  when: manual
  only:
    - tags