---
- name: Apply base configuration
  hosts: all
  become: yes
  
  tasks:
    - name: Set timezone
      timezone:
        name: "{{ time.timezone }}"
      
    - name: Configure DNS
      template:
        src: "resolv.conf.j2"
        dest: "/etc/resolv.conf"
        owner: root
        group: root
        mode: 0644
      
    - name: Create admin users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: /bin/bash
        ssh_key: "{{ item.ssh_keys | first }}"
        append: yes
      loop: "{{ system_users.admins }}"