---
# SSH Configuration
ssh:
  port: 2222
  permit_root_login: false
  password_authentication: false
  allowed_users:
    - devops
    - deploy

# Firewall Rules
firewall:
  enabled: true
  allowed_tcp_ports:
    - "{{ ssh.port }}"
    - 80
    - 443
    - 9090

# Security Packages
security_packages:
  - fail2ban
  - unattended-upgrades