---
# Service Endpoints
endpoints:
  api: "https://api.example.com"
  db: "db.internal.example.com"
  monitoring: "https://monitor.example.com"

# Backup Configuration
backup:
  schedule: "0 3 * * *"
  retention_days: 7
  include:
    - /etc
    - /var/www
  exclude:
    - /tmp
    - /var/cache

# Monitoring Setup
monitoring:
  prometheus:
    scrape_interval: 30s
  alertmanager:
    slack_webhook: "!vault|..."