---
- name: Setup SSH Public Key
  hosts: all
  become: yes
  vars:
    ssh_public_key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzf8YMVRqkhSzJNqJpPwo9VqJC25J1CQ+xSN/+fVYjKn6koG8A/9BHNj07OhCBa90Z+83qlSKmQYZ/ZgkT2UpzjRZAxVRzRlt1tLMbDhbgxAGZe96CyJypspia4+Dg+IROTMLKAY6VauWtlI10WS89BEhYJ0DHbwmQmTlPpIjd7EGUNmMivfQku36Jg3sQ6EHx4FkXNojg+qbtnUfYcKjE3gbMDettGaK4cVn8MJ5oWgD9L8B7VHfFlEr7o7QTk41tCI36rpT1RCwOHRgSpS5kbQo+/ed5vSXnuhy/BxFjj2WjHwPIcynw4ZJcBVKLP1IiPGrorTxECXfhTn5VQngaQIDAQAB"  # کلید عمومی شما اینجا قرار می‌گیرد
    ansible_user: "j"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key }}"
        manage_dir: no

    - name: Secure SSH config
      block:
        - name: Disable password authentication
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PasswordAuthentication'
            line: 'PasswordAuthentication no'
            state: present
          notify:
            - restart sshd

        - name: Disable root login
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: 'PermitRootLogin no'
            state: present
          notify:
            - restart sshd

      handlers:
        - name: restart sshd
          service:
            name: sshd
            state: restarted