- name: Deploy SSH key
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  
  tasks:
    - name: Create .ssh directory
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700

    - name: Install private key
      copy:
        content: "{{ ssh_private_key }}"
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
        mode: 0600