---
- name: Install and Configure GitLab on Rocky Linux
  hosts: all
  become: true
  vars:
    gitlab_data_dir: "/srv/gitlab"
    gitlab_external_url: "http://{{ ansible_default_ipv4.address }}"
    gitlab_ssh_port: 2222

  tasks:
    # 1: prerequirements Docker-ce
    - name: Install required packages
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker CE
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ 'linux' if ansible_system == 'Linux' else 'darwin' }}-{{ 'x86_64' if ansible_architecture == 'x86_64' else 'aarch64' }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # 2 : config Docker
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Configure Docker daemon
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Reload Docker daemon
      command: systemctl reload docker

    # 3: run gitlab 
    - name: Create GitLab directories
      file:
        path: "{{ gitlab_data_dir }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - config
        - logs
        - data

    - name: Create docker-compose.yml for GitLab
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ gitlab_data_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Run GitLab container
      community.docker.docker_compose:
        project_src: "{{ gitlab_data_dir }}"
        state: present

    - name: Open firewall ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 80
        - 443
        - "{{ gitlab_ssh_port }}"