---
- name: Install Kubernetes (k3s)
  shell: |
    curl -sfL https://get.k3s.io | sh -
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

- name: Deploy Sample Microservice
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sample-service
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80